import { BrainwaveState, SessionPreset } from './types';

export const BRAINWAVE_STATES = [
  {
    id: 'delta' as BrainwaveState,
    name: 'Delta',
    range: '0.5–4 Hz',
    defaultFreq: 2,
    min: 0.5,
    max: 4,
    description: 'Deep sleep, healing, and restorative rest',
    icon: '😴',
    color: '#6366f1',
    bgClass: 'bg-indigo-500/10 border-indigo-500/20',
    activeClass: 'bg-indigo-500/20 border-indigo-500',
  },
  {
    id: 'theta' as BrainwaveState,
    name: 'Theta',
    range: '4–8 Hz',
    defaultFreq: 6,
    min: 4,
    max: 8,
    description: 'Deep meditation, creativity, and REM sleep',
    icon: '🧘',
    color: '#8b5cf6',
    bgClass: 'bg-purple-500/10 border-purple-500/20',
    activeClass: 'bg-purple-500/20 border-purple-500',
  },
  {
    id: 'alpha' as BrainwaveState,
    name: 'Alpha',
    range: '8–13 Hz',
    defaultFreq: 10,
    min: 8,
    max: 13,
    description: 'Relaxed focus, stress reduction, and light meditation',
    icon: '😌',
    color: '#14b8a6',
    bgClass: 'bg-teal-500/10 border-teal-500/20',
    activeClass: 'bg-teal-500/20 border-teal-500',
  },
  {
    id: 'beta' as BrainwaveState,
    name: 'Beta',
    range: '13–30 Hz',
    defaultFreq: 18,
    min: 13,
    max: 30,
    description: 'Active thinking, focus, alertness, and cognition',
    icon: '🎯',
    color: '#f59e0b',
    bgClass: 'bg-amber-500/10 border-amber-500/20',
    activeClass: 'bg-amber-500/20 border-amber-500',
  },
  {
    id: 'gamma' as BrainwaveState,
    name: 'Gamma',
    range: '30–100 Hz',
    defaultFreq: 40,
    min: 30,
    max: 100,
    description: 'Peak performance, problem solving, and high-level processing',
    icon: '⚡',
    color: '#ef4444',
    bgClass: 'bg-red-500/10 border-red-500/20',
    activeClass: 'bg-red-500/20 border-red-500',
  },
];

export const BUILT_IN_PRESETS: SessionPreset[] = [
  {
    id: 'deep-work',
    name: 'Deep Work',
    description: 'Brown noise + Beta waves for intense focus sessions',
    icon: '🎯',
    category: 'focus',
    settings: {
      noise: { enabled: true, type: 'brown', volume: 0.6 },
      tone: { enabled: true, brainwaveState: 'beta', frequency: 18, volume: 0.3, type: 'isochronic' },
      effects: { eightD: false, lofi: false, crackles: 0, pops: 0, echo: 0, reverb: 0, distortion: 0 },
      duration: 90 * 60,
      fadeIn: 30,
      fadeOut: 60,
    },
  },
  {
    id: 'lofi-library',
    name: 'Lo-Fi Library',
    description: 'Muffled library ambiance with vinyl crackle and Alpha focus.',
    icon: '☕',
    category: 'focus',
    isPremium: false,
    settings: {
      noise: { enabled: true, type: 'pink', volume: 0.4 },
      tone: { enabled: true, brainwaveState: 'alpha', frequency: 10, volume: 0.2, type: 'binaural' },
      effects: { eightD: false, lofi: true, crackles: 0.3, pops: 0.3, echo: 0, reverb: 0, distortion: 0.2 },
      duration: 60 * 60,
      fadeIn: 15,
      fadeOut: 30,
    },
  },
  {
    id: 'eight-d-meditation',
    name: '8D Space Walk',
    description: 'Spherical Theta waves that rotate around your head.',
    icon: '👩‍🚀',
    category: 'relax',
    isPremium: true,
    settings: {
      noise: { enabled: true, type: 'brown', volume: 0.2 },
      tone: { enabled: true, brainwaveState: 'theta', frequency: 6, volume: 0.4, type: 'binaural' },
      effects: { eightD: true, lofi: false, crackles: 0, pops: 0, echo: 0.2, reverb: 0.4, distortion: 0 },
      duration: 30 * 60,
      fadeIn: 60,
      fadeOut: 60,
    },
  },
  {
    id: 'cyberpunk-focus',
    name: 'Neon Concentration',
    description: 'Expert-designed Pink noise with Beta peaks for creative flow.',
    icon: '🌃',
    category: 'focus',
    isPremium: true,
    settings: {
      noise: { enabled: true, type: 'pink', volume: 0.7 },
      tone: { enabled: true, brainwaveState: 'beta', frequency: 15, volume: 0.4, type: 'isochronic' },
      effects: { eightD: false, lofi: false, crackles: 0, pops: 0, echo: 0, reverb: 0, distortion: 0 },
      duration: 60 * 60,
      fadeIn: 120,
      fadeOut: 60,
    },
  },
  {
    id: 'zen-garden',
    name: 'Eternal Garden',
    description: 'Complex Theta waves synced to the Schumann resonance.',
    icon: '🎋',
    category: 'relax',
    isPremium: true,
    settings: {
      noise: { enabled: true, type: 'brown', volume: 0.3 },
      tone: { enabled: true, brainwaveState: 'theta', frequency: 7.83, volume: 0.5, type: 'binaural' },
      effects: { eightD: true, lofi: false, crackles: 0, pops: 0, echo: 0.1, reverb: 0.5, distortion: 0 },
      duration: 45 * 60,
      fadeIn: 60,
      fadeOut: 300,
    },
  },
  {
    id: 'deep-sleep',
    name: 'Deep Sleep',
    description: 'Brown noise + Delta waves for restorative rest',
    icon: '😴',
    category: 'sleep',
    settings: {
      noise: { enabled: true, type: 'brown', volume: 0.5 },
      tone: { enabled: true, brainwaveState: 'delta', frequency: 2, volume: 0.2, type: 'isochronic' },
      effects: { eightD: false, lofi: false, crackles: 0, pops: 0, echo: 0, reverb: 0, distortion: 0 },
      duration: 8 * 60 * 60,
      fadeIn: 60,
      fadeOut: 0,
    },
  },
];
