
import React, { useState } from 'react';
import {
  Youtube, Instagram, Music, X, Check, ArrowRight,
  Share2, Calendar, Globe, Loader2, Sparkles, Send,
  ChevronRight, Layout, Settings2, Link2, AlertCircle, Lock, Crown
} from 'lucide-react';
import { SocialPlatform, PlatformMetadata } from '../types';
import { useStore } from '../store';
import ProModal from './ProModal';

interface ExportModalProps {
  onClose: () => void;
}

const ExportModal: React.FC<ExportModalProps> = ({ onClose }) => {
  const { addPublishedItem, visualAssets, user } = useStore();
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [selectedPlatforms, setSelectedPlatforms] = useState<SocialPlatform[]>(['youtube']);
  const [isPublishing, setIsPublishing] = useState(false);
  const [activePlatformTab, setActivePlatformTab] = useState<SocialPlatform>('youtube');
  const [removeBranding, setRemoveBranding] = useState(false);
  const [showProModal, setShowProModal] = useState(false);

  const connectedPlatforms: SocialPlatform[] = ['youtube', 'tiktok', 'instagram'];

  const [metadata, setMetadata] = useState<Record<SocialPlatform, PlatformMetadata>>({
    youtube: { title: "Midnight Odyssey - Lo-Fi Beats [OrbitAudio AI]", description: "Chilled lofi beats generated with OrbitAudio AI.", tags: ["lofi", "ai", "synthwave"], visibility: 'public' },
    tiktok: { title: "Vibe check 🌙 #lofi #ai", description: "", tags: ["lofi", "ai"], visibility: 'public' },
    instagram: { title: "New drop! Link in bio. 🎧", description: "Created with @OrbitAudioAI", tags: ["synthwave", "chill"], visibility: 'public' },
    x: { title: "New music generated by AI. 🚀", description: "", tags: ["AI", "MusicGen"], visibility: 'public' },
    facebook: { title: "Check out my latest AI track!", description: "", tags: ["music"], visibility: 'public' },
    spotify: { title: "Midnight Odyssey", description: "An AI generated lofi masterpiece.", tags: ["lofi", "instrumental"], visibility: 'public' },
  });

  const updatePlatformMetadata = (platform: SocialPlatform, updates: Partial<PlatformMetadata>) => {
    setMetadata(prev => ({ ...prev, [platform]: { ...prev[platform], ...updates } }));
  };

  const handlePublish = () => {
    setIsPublishing(true);
    setTimeout(() => {
      const newItem = {
        id: Math.random().toString(36).substr(2, 9),
        title: metadata[selectedPlatforms[0]].title,
        thumbnailUrl: visualAssets[0]?.url || 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?w=200&h=200&fit=crop',
        publishDate: new Date().toISOString(),
        status: 'published' as const,
        stats: selectedPlatforms.map(p => ({ platform: p, views: 0, likes: 0, url: '#' }))
      };
      addPublishedItem(newItem);
      setIsPublishing(false);
      onClose();
    }, 2500);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 backdrop-blur-md p-4" onClick={onClose}>
      <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2.5rem] w-full max-w-3xl h-[640px] shadow-2xl overflow-hidden flex flex-col" onClick={e => e.stopPropagation()}>
        <div className="px-8 py-6 border-b border-zinc-100 dark:border-zinc-800 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
              <Share2 size={20} className="text-cyan-500" /> Share Masterpiece
            </h2>
            <p className="text-[10px] text-zinc-500 font-bold uppercase tracking-widest mt-0.5">Export and publish cross-platform</p>
          </div>
          <button onClick={onClose} className="p-2 text-zinc-400 hover:text-zinc-100"><X size={24} /></button>
        </div>

        <div className="flex-1 overflow-hidden flex">
          {/* Sidebar */}
          <div className="w-48 border-r border-zinc-100 dark:border-zinc-800 bg-zinc-50/30 dark:bg-zinc-950/20 p-8 flex flex-col">
            <div className="flex flex-col gap-6">
              {[
                { s: 1, label: 'Platforms', icon: <Layout size={14} /> },
                { s: 2, label: 'Metadata', icon: <Settings2 size={14} /> },
                { s: 3, label: 'Mastering', icon: <Globe size={14} /> }
              ].map(({ s, label, icon }) => (
                <div key={s} className={`flex items-center gap-3 ${step === s ? 'text-cyan-500' : 'text-zinc-400 dark:text-zinc-600'}`}>
                  <div className={`w-8 h-8 rounded-xl flex items-center justify-center border ${step === s ? 'bg-cyan-500 text-white border-cyan-400' : 'bg-zinc-100 dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800'}`}>
                    {icon}
                  </div>
                  <span className="text-[10px] font-black uppercase tracking-widest">{label}</span>
                </div>
              ))}
            </div>

            {/* Monetization Feature: White Labeling */}
            <div className="mt-auto p-4 bg-zinc-100 dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-zinc-800">
              <div className="flex items-center justify-between mb-3">
                <span className="text-[9px] font-black uppercase text-zinc-400">White Label</span>
                {!user?.isPro && <Lock size={10} className="text-zinc-500" />}
              </div>
              <button
                onClick={() => user?.isPro ? setRemoveBranding(!removeBranding) : setShowProModal(true)}
                className={`w-full py-2 rounded-lg text-[8px] font-black uppercase tracking-widest transition ${removeBranding ? 'bg-emerald-500 text-white' : 'bg-zinc-200 dark:bg-zinc-800 text-zinc-500'}`}
              >
                {removeBranding ? 'Branding Removed' : 'Remove Watermark'}
              </button>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-10 custom-scrollbar">
            {step === 1 && (
              <div className="grid grid-cols-2 gap-4">
                {(['youtube', 'tiktok', 'instagram', 'spotify'] as const).map(p => (
                  <button
                    key={p}
                    onClick={() => setSelectedPlatforms(prev => prev.includes(p) ? prev.filter(x => x !== p) : [...prev, p])}
                    className={`p-5 rounded-[2rem] border flex flex-col items-center gap-2 ${selectedPlatforms.includes(p) ? 'bg-cyan-500 text-white border-cyan-400 shadow-lg' : 'bg-zinc-50 dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 text-zinc-500'}`}
                  >
                    {p === 'youtube' && <Youtube size={24} />}
                    {p === 'tiktok' && <Music size={24} />}
                    {p === 'instagram' && <Instagram size={24} />}
                    <span className="text-[10px] font-black uppercase tracking-widest">{p}</span>
                  </button>
                ))}
              </div>
            )}

            {step === 2 && (
              <div className="space-y-4">
                <div className="p-4 bg-zinc-50 dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-zinc-800 space-y-4">
                  <input
                    className="w-full bg-white dark:bg-zinc-950 p-3 rounded-lg text-xs"
                    value={metadata[activePlatformTab].title}
                    onChange={(e) => updatePlatformMetadata(activePlatformTab, { title: e.target.value })}
                  />
                  <textarea
                    className="w-full bg-white dark:bg-zinc-950 p-3 rounded-lg text-xs h-24"
                    value={metadata[activePlatformTab].description}
                    onChange={(e) => updatePlatformMetadata(activePlatformTab, { description: e.target.value })}
                  />
                </div>
              </div>
            )}

            {step === 3 && (
              <div className="space-y-6">
                <div className="p-6 bg-gradient-to-br from-indigo-600 to-cyan-500 rounded-[2rem] text-white shadow-2xl relative overflow-hidden">
                  <div className="absolute top-0 right-0 p-8 opacity-10"><Crown size={120} /></div>
                  <h3 className="text-xl font-black italic tracking-tighter mb-2">MASTERING SUITE</h3>
                  <p className="text-xs opacity-80 mb-6 font-medium">Applying loudness optimization and dynamic compression for professional platform compliance.</p>

                  <div className="flex gap-4">
                    <div className="bg-white/10 p-3 rounded-xl backdrop-blur-md">
                      <div className="text-[8px] font-black uppercase tracking-widest opacity-50">Res</div>
                      <div className="text-xs font-bold">{user?.isPro ? '4K Ultra' : '1080p Standard'}</div>
                    </div>
                    <div className="bg-white/10 p-3 rounded-xl backdrop-blur-md">
                      <div className="text-[8px] font-black uppercase tracking-widest opacity-50">Loudness</div>
                      <div className="text-xs font-bold">-14.0 LUFS</div>
                    </div>
                  </div>
                </div>

                {!user?.isPro && (
                  <div className="p-6 border border-dashed border-zinc-200 dark:border-zinc-800 rounded-[2rem] flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Crown size={24} className="text-amber-500" />
                      <div className="text-xs font-bold text-zinc-900 dark:text-zinc-100">Unlock 4K & Unlimited Length</div>
                    </div>
                    <button onClick={() => setShowProModal(true)} className="px-4 py-2 bg-zinc-900 dark:bg-zinc-100 text-zinc-100 dark:text-zinc-900 text-[10px] font-black uppercase rounded-xl">Upgrade</button>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        <div className="px-10 py-8 bg-zinc-50 dark:bg-zinc-950 border-t border-zinc-100 dark:border-zinc-800 flex items-center justify-end gap-4">
          {step > 1 && (
            <button onClick={() => setStep((step - 1) as any)} className="px-8 py-4 text-zinc-400 text-xs font-black uppercase tracking-widest">Back</button>
          )}
          {step < 3 ? (
            <button onClick={() => setStep((step + 1) as any)} className="px-10 py-4 bg-zinc-900 dark:bg-zinc-100 text-zinc-100 dark:text-zinc-900 rounded-2xl text-xs font-black uppercase tracking-[0.2em] flex items-center gap-2">Next <ChevronRight size={18} /></button>
          ) : (
            <button onClick={handlePublish} disabled={isPublishing} className="px-12 py-4 bg-cyan-600 text-white rounded-2xl text-xs font-black uppercase tracking-[0.2em] shadow-xl shadow-cyan-500/30 flex items-center gap-2">
              {isPublishing ? <Loader2 size={18} className="animate-spin" /> : <Send size={18} />}
              {isPublishing ? 'Broadcasting...' : 'Blast Out'}
            </button>
          )}
        </div>
      </div>
      {showProModal && <ProModal onClose={() => setShowProModal(false)} />}
    </div>
  );
};

export default ExportModal;
